#!/usr/bin/env python3
"""Run a bounded, loopback-only MCP Gateway demo and write a stable transcript."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import pathlib
import re
import select
import signal
import socket
import subprocess
import tempfile
import time
import urllib.request
from typing import IO

ROOT = pathlib.Path(__file__).resolve().parents[1]
DEFAULT_ARTIFACT = ROOT / "docs" / "demo-output.md"
PROCESS_TIMEOUT_SECONDS = 15


def normalize_transcript(text: str) -> str:
    """Replace nondeterministic loopback ports in displayed URLs."""
    return re.sub(r"(?<=127\.0\.0\.1:)\d+", "<PORT>", text)


def render_artifact(*, client_body: str, audit_status: int, audit_result: str) -> str:
    compact_body = json.dumps(json.loads(client_body), sort_keys=True, separators=(",", ":"))
    return (
        "# Reproducible MCP Gateway demo\n\n"
        "> Generated by `python3 scripts/demo.py`; source milestone only—no tag or release.\n\n"
        "The demo builds the gateway and example binaries, starts a loopback MCP server, "
        "sends an authenticated `tools/call` through the gateway, and validates the audit event.\n\n"
        f"- HTTP status: `{audit_status}`\n"
        f"- Audit result: `{audit_result}`\n"
        f"- Client response: `{compact_body}`\n"
        "- Credential exposure check: passed (fixture value absent from output and gateway logs)\n"
    )


def free_loopback_port() -> int:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as listener:
        listener.bind(("127.0.0.1", 0))
        return int(listener.getsockname()[1])


def wait_for_url(url: str, deadline: float) -> None:
    while time.monotonic() < deadline:
        try:
            with urllib.request.urlopen(url, timeout=0.5) as response:
                if response.status == 200:
                    return
        except OSError:
            time.sleep(0.05)
    raise RuntimeError("demo service did not become healthy before the deadline")


def read_line_with_deadline(stream: IO[str], timeout_seconds: float) -> str:
    """Read one short child-process line without allowing a silent/partial hang."""
    deadline = time.monotonic() + timeout_seconds
    characters = bytearray()
    descriptor = stream.fileno()
    while time.monotonic() < deadline and len(characters) <= 512:
        remaining = deadline - time.monotonic()
        readable, _, _ = select.select([descriptor], [], [], max(0, remaining))
        if not readable:
            break
        character = os.read(descriptor, 1)
        if character == b"":
            break
        if character == b"\n":
            try:
                return characters.decode("ascii")
            except UnicodeDecodeError as error:
                raise RuntimeError("example MCP server reported non-ASCII output") from error
        characters.extend(character)
    raise RuntimeError("example MCP server did not report output before the deadline")


def stop_process(process: subprocess.Popen[str] | None) -> None:
    if process is None or process.poll() is not None:
        return
    process.send_signal(signal.SIGTERM)
    try:
        process.wait(timeout=5)
    except subprocess.TimeoutExpired:
        process.kill()
        try:
            process.wait(timeout=2)
        except subprocess.TimeoutExpired:
            # Continue the outer finally block so another child is not leaked.
            pass


def build(binary: pathlib.Path, package: str) -> None:
    subprocess.run(
        ["go", "build", "-o", str(binary), package],
        cwd=ROOT,
        env={**os.environ, "GOMAXPROCS": "1"},
        check=True,
        timeout=60,
    )


def run_demo() -> str:
    fixture_value = "mcp-gateway-local-demo-value"
    fixture_digest = hashlib.sha256(fixture_value.encode()).hexdigest()
    upstream: subprocess.Popen[str] | None = None
    gateway: subprocess.Popen[str] | None = None
    gateway_log_handle = None

    with tempfile.TemporaryDirectory(prefix="mcp-gateway-demo-") as temporary:
        temp = pathlib.Path(temporary)
        gateway_binary = temp / "mcp-gateway"
        server_binary = temp / "mcpserver"
        client_binary = temp / "mcpclient"
        for binary, package in (
            (gateway_binary, "./cmd/mcp-gateway"),
            (server_binary, "./examples/mcpserver"),
            (client_binary, "./examples/mcpclient"),
        ):
            build(binary, package)

        upstream = subprocess.Popen(
            [str(server_binary)],
            cwd=ROOT,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
        try:
            assert upstream.stdout is not None
            address_line = read_line_with_deadline(upstream.stdout, 5)
            if not re.fullmatch(r"MCP_SERVER_ADDR=127\.0\.0\.1:\d+", address_line):
                raise RuntimeError("example MCP server did not report a safe loopback address")
            upstream_address = address_line.split("=", 1)[1]

            gateway_port = free_loopback_port()
            gateway_log = temp / "gateway.log"
            gateway_log_handle = gateway_log.open("w+", encoding="utf-8")
            gateway_env = {
                **os.environ,
                "MCP_GATEWAY_UPSTREAM_URL": f"http://{upstream_address}/mcp",
                "MCP_GATEWAY_LISTEN_ADDRESS": f"127.0.0.1:{gateway_port}",
                "MCP_GATEWAY_UPSTREAM_TIMEOUT": "5s",
                "MCP_GATEWAY_READ_TIMEOUT": "5s",
                "MCP_GATEWAY_WRITE_TIMEOUT": "8s",
                "MCP_GATEWAY_IDLE_TIMEOUT": "30s",
                "MCP_GATEWAY_MAX_REQUEST_BYTES": "1048576",
                "MCP_GATEWAY_MAX_RESPONSE_BYTES": "1048576",
                "MCP_GATEWAY_MAX_IN_FLIGHT": "4",
                "MCP_GATEWAY_MAX_SAFE_RETRIES": "0",
                "MCP_GATEWAY_API_KEYS": f"demo-client={fixture_digest}",
                "MCP_GATEWAY_TOOL_POLICIES": "demo-client:echo=allow",
                "MCP_GATEWAY_TOOL_RATE_LIMITS": "demo-client:echo=2/1s",
                "MCP_GATEWAY_AUDIT_REDACT": "request_id",
            }
            gateway = subprocess.Popen(
                [str(gateway_binary)],
                cwd=ROOT,
                env=gateway_env,
                stdout=gateway_log_handle,
                stderr=subprocess.STDOUT,
                text=True,
            )
            wait_for_url(f"http://127.0.0.1:{gateway_port}/readyz", time.monotonic() + 5)

            payload = json.dumps(
                {
                    "jsonrpc": "2.0",
                    "id": 2,
                    "method": "tools/call",
                    "params": {"name": "echo", "arguments": {"text": "gateway-demo-ok"}},
                },
                separators=(",", ":"),
            )
            client = subprocess.run(
                [str(client_binary), "-gateway-url", f"http://127.0.0.1:{gateway_port}/mcp", "-request-id", "demo-request-1"],
                cwd=ROOT,
                env={**os.environ, "MCP_CLIENT_KEY": fixture_value},
                input=payload,
                text=True,
                capture_output=True,
                check=True,
                timeout=PROCESS_TIMEOUT_SECONDS,
            )
            decoded = json.loads(client.stdout)
            content = decoded.get("result", {}).get("content", [])
            if content != [{"text": "gateway-demo-ok", "type": "text"}]:
                raise RuntimeError("demo client did not receive the expected echo result")

            gateway_log_handle.flush()
            deadline = time.monotonic() + 2
            audit: dict[str, object] | None = None
            while time.monotonic() < deadline:
                gateway_log_handle.seek(0)
                for line in gateway_log_handle:
                    try:
                        event = json.loads(line)
                    except json.JSONDecodeError:
                        continue
                    if event.get("msg") == "mcp audit event":
                        audit = event
                if audit is not None:
                    break
                time.sleep(0.05)
            gateway_log_handle.seek(0)
            logs = gateway_log_handle.read()
            if fixture_value in logs or fixture_value in client.stdout or fixture_value in client.stderr:
                raise RuntimeError("demo fixture value appeared in output")
            if audit is None or audit.get("status") != 200 or audit.get("result_class") != "success" or audit.get("reason") != "":
                raise RuntimeError("demo did not produce the expected successful audit event")
            status = audit.get("status")
            result = audit.get("result_class")
            if not isinstance(status, int) or not isinstance(result, str):
                raise RuntimeError("demo audit event has invalid field types")
            return render_artifact(
                client_body=client.stdout.strip(),
                audit_status=status,
                audit_result=result,
            )
        finally:
            stop_process(gateway)
            stop_process(upstream)
            if gateway_log_handle is not None:
                gateway_log_handle.close()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the checked artifact differs")
    parser.add_argument("--output", type=pathlib.Path, default=DEFAULT_ARTIFACT)
    args = parser.parse_args()

    artifact = run_demo()
    if args.check:
        if not args.output.exists() or args.output.read_text(encoding="utf-8") != artifact:
            raise SystemExit("demo artifact is stale; run python3 scripts/demo.py")
        print("demo artifact is reproducible and current")
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(artifact, encoding="utf-8")
    print(f"wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
